name: znn_decay_calculator
description: calculates amount of ZNN and QSR lost to swap decay
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dcli: ^1.7.1
  znn_sdk_dart:
    git:
      #url: https://github.com/zenon-network/znn_sdk_dart.git
      #ref: 367ddc7fbfefb6484d7553d9ac7e4532003a7008
      url: https://github.com/sol-sanctum/znn_sdk_dart.git
      ref: spork_htlc