name: Parse network data and publish *.json files

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 */6 * * *'    # Every 6 hours
  workflow_dispatch:

jobs:
  generate-znn-node-info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f znn_node_info/requirements.txt ]; 
            then pip install -r ./znn_node_info/requirements.txt; 
        fi
    - name: Produce Release files
      run: cd znn_node_info && python main.py
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: znn_node_info/data/*.json
        tag: znn_node_info
        file_glob: true
        overwrite: true
        body: ""