name: znn_message_signer
description: tool to parse momentums for specific criteria
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  path: ^1.8.0
  os_detect: ^2.0.1
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git
      ref: 367ddc7fbfefb6484d7553d9ac7e4532003a7008
